# Generated by Django 5.1.6 on 2025-02-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambrehotel',
            name='disponibilite',
            field=models.BooleanField(choices=[(0, 'Non'), (1, 'Oui')], default=0),
        ),
        migrations.AlterField(
            model_name='chambrehotel',
            name='petit_dejeuner',
            field=models.BooleanField(choices=[(0, 'Non'), (1, 'Oui')], default=0),
        ),
    ]
