# Generated by Django 5.1.6 on 2025-02-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_chambrehotel_disponibilite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambrehotel',
            name='type',
            field=models.CharField(choices=[(0, 'Simple'), (1, 'Double'), (2, 'Suite'), (3, 'Appartement'), (4, 'Penthouse')], default=0),
        ),
    ]
